### ISSUE TITLE
win 10 installation problem

### ISSUE THREAD

**Issue by tpyb** [michaelpq/pg_plugins#33]
The .so file compiled by gcc on Linux has been verified to run successfully;
vs 2013 compiled .dll file on win10 (compiled successfully), an error is reported during verification:

ERROR: could not find function "blackhole_am_handler" in file "xxxx".

the problem caused by compilation? Has anyone tested this plugin successfully on win10? Can you provide a compilation method, or directly provide me the blackhole_am.dll file to try it?

**Comment by tpyb** [comment]
solved;
For each function you have a PG_FUNCTION_INFO_V1 for, i.e. it's to be exported as a C extension function, prepend PGDLLEXPORT before the Datum return value.
Reference: https://wiki.postgresql.org/wiki/Building_and_Installing_PostgreSQL_Extension_Modules#Windows_with_Microsoft_Visual_Studio

**Comment by michaelpq** [comment]
If you think something is wrong, could you send a patch? FWIW, blackhole_am declares blackhole_am_handler with PG_FUNCTION_INFO_V1, which would assign PGDLLEXPORT already.

Supporting the build of those modules is not something I am directly interested in supported in this repository as of now, because:
1) I have no testing facility to check after it automatically.
2) It is a rather painful experience to integrate a module to build with the upstream perl APIs for MSVC build in src/tools/msvc/. Once the integration experience gets better upstream (aka less code maintenance to worry about here), I think that we could consider something for this set of modules.
