### ISSUE TITLE
A hooked function should keep the chain going

### ISSUE THREAD

**Issue by eremmel** [michaelpq/pg_plugins#7]
Hi Micheal, Thanks for your quick response to my remark. Because I'm not a native English speaker I'm sorry that I pointed you into the wrong direction.

As far as I understand the function EmitErrorReport () in  elog.c, it just calls the last registered hook:
|    if (edata->output_to_server && emit_log_hook)
|            (*emit_log_hook) (edata);
So you have to keep the chain going. Because your plugin is a replacement of the logger, I think it is good to set 'edata->output_to_server' to false as original done. I think that you need to do something like the following near the beginning of write_jsonlog():
	StringInfoData	buf;
	TransactionId	txid = GetTopTransactionIdIfAny();

+	/* First honor other hooked log extensions */
+	if ( prev_log_hook )
+	{
+		(*prev_log_hook)(edata);
+		/* An other extension direct us to ignore the message */
+		if ( edata->output_to_server == false )
+			return;
+	}
+
	initStringInfo(&buf);

I made a hook that ignored the reporting of error 23505 (ERRCODE_UNIQUE_VIOLATION) when log_min_messages >= ERROR && log_min_error_statement >= ERROR. This will work nicely now with your plugin, independent on the load order of both plugins.

Regards,
Erik

**Comment by michaelpq** [comment]
Oh, no. Your idea was right, we should definitely not enforce output_to_server in the plugin but let the server deal with that :)

Regarding the call to the previous hook, if defined, you are right again but I think that it should be called at the bottom of the plugin instead of the top as you are mentioning, like that:
        /* Cleanup */
        pfree(buf.data);
+
+       /* Continue chain to previous hook */
+       if (prev_log_hook)
+               (*prev_log_hook) (edata);

So that's what I did in b87023a8.
